# Generated by Django 5.2.4 on 2025-07-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
